runtime: python37
instance_class: F4
automatic_scaling:
  max_instances: 50
  max_idle_instances: 10

handlers:
- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /partials
  static_dir: static/partials
  secure: always

- url: /fonts
  static_dir: static/fonts
  secure: always

- url: /third_party
  static_dir: static/third_party
  secure: always

- url: /createdb
  secure: always
  script: auto

- url: /.*
  secure: always
  script: auto
